# 데이터 경로
rating_file_path: '../../data/train/train_ratings.csv'

# 출력 디렉토리
model_save_dir: './saved_models'
output_dir: './output'  # Changed from 'outputs' to 'output'

# 데이터 분할 설정
test_size: 0.2
seed: 42

# 모델 하이퍼파라미터
hidden_dim: 600
latent_dim: 200
dropout_prob: 0.5
learning_rate: 0.001

# 훈련 설정
epochs: 300
batch_size: 128
total_anneal_steps: 200000
anneal_cap: 0.2

# 평가 설정
recall_k: 10
top_k_recommendations: 10

# Logging
log_dir: './logs'

# Early Stopping
early_stopping_patience: 10
early_stopping_delta: 0.001